doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App\Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Entity'
                prefix: 'App\Core\Entity'
                alias: App\Core
            App\Core\Game:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Game/Entity'
                prefix: 'App\Core\Game\Entity'
                alias: App\Core\Game
            App\Core\Node:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Node/Entity'
                prefix: 'App\Core\Node\Entity'
                alias: App\Core\Node
            App\Core\User\:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/User/Entity'
                prefix: 'App\Core\User\Entity'
                alias: App\Core\User
