services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\Infrastructure\Persistence\Doctrine\Repository\Game\GameRepository: ~

  App\Core\Game\GameRepositoryInterface:
    alias: App\Infrastructure\Persistence\Doctrine\Repository\Game\GameRepository

  App\Core\Game\GameContextRepositoryInterface:
    alias: App\Infrastructure\Persistence\Doctrine\Repository\Game\GameContextRepository

  App\Core\Game\CharacteristicRepositoryInterface:
    alias: App\Infrastructure\Persistence\Doctrine\Repository\Game\CharacteristicRepository

  App\Core\Game\GameConstraintRepositoryInterface:
    alias: App\Infrastructure\Persistence\Doctrine\Repository\Game\GameConstraintRepository
