jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"

services:
    App\Core\Utils\Serialization\SerializerFactory: ~

    camel_case_serializer:
        class: 'JMS\Serializer\SerializerInterface'
        factory: ['@App\Core\Utils\Serialization\SerializerFactory', 'createCameCaseSerializer']

    identical_serializer:
        class: 'JMS\Serializer\SerializerInterface'
        factory: ['@App\Core\Utils\Serialization\SerializerFactory', 'createIdenticalPropertySerializer']
