knp_paginator:
  page_range: 20 # number of links shown in pagination menu
  default_options:
    page_name: page # page query parameter name
    sort_field_name: sort # sort field query parameter name
    sort_direction_name: direction # sort direction query parameter name
    distinct: true # ensure distinct results, useful when ORM queries are using GROUP BY statements
    filter_field_name: filterField # filter field query query parameter name
    filter_value_name: filterValue # filter value query query parameter name
  template:
      pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'     # sliding pagination controls template
      sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
      filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template


