services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\Infrastructure\Persistence\Doctrine\Repository\Node\NodeRepository: ~

  App\Core\Node\NodeRepositoryInterface:
    alias: App\Infrastructure\Persistence\Doctrine\Repository\Node\NodeRepository

  App\Infrastructure\Persistence\Doctrine\Repository\Answer\AnswerRepository: ~

  App\Core\Answer\AnswerRepositoryInterface:
    alias: App\Infrastructure\Persistence\Doctrine\Repository\Answer\AnswerRepository