version: '3.7'

services:
  botstory-php:
#    container_name: php
#    image: php
    build:
      context: ./php
    volumes:
      - ../:/srv/botstory/current
  botstory-nginx:
#    container_name: nginx
#    image: nginx
    build:
      context: ./nginx
    volumes:
      - ../:/srv/botstory/current
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - botstory-php
    ports:
      - "80:80"

  botstory-mysql:
    image: mysql:8.0
#    container_name: mysql
    environment:
      MYSQL_USER: botstory
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: botstory
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data-botstory:/var/lib/mysql:rw
    ports:
      - '3306:3306'
    expose:
      - '3306'

volumes:
  db-data-botstory: {}
